# Prácticas de la 1 a la 2.1
#==============================
IP_pub: 192.168.18.225/24
Red_dst: "172.1.1.0/24"
GW: "192.168.18.224"
IP_interna: "10.1.1.1/24"
Red_interna: "10.1.1.0"
Red_int_mask: "10.1.1.0/24"
Mask: "255.255.255.0"
Rango_dhcp_inicio: "10.1.1.3"
Rango_dhcp_final: "10.1.1.10"
Gateway_dhcp: "10.1.1.1"
IP_fija_dhcp: "10.1.1.11"
Cliente: "cliente2"
Mac_cliente: "{{ hostvars['cliente2'].ansible_enp0s8.macaddress }}"
Dominio: "altea.es"

## Práctica 3.1 - https://github.com/bertvv/ansible-role-bind
#=============================================================
IP_fija_cliente: "10.1.1.11"
Forwarders: ['208.67.222.222','1.1.1.1']

bind_acls:
  - name: confiables
    match_list:
      - "{{ Red_int_mask }}"
      - "{{ GW }}"
bind_listen_ipv4:
  - "{{ Gateway_dhcp }}"
  - "{{ IP_pub.split('/')[0] }}"
bind_recursion: true
bind_allow_recursion: ['confiables']
bind_allow_query: ['confiables']
bind_forwarders: "{{ Forwarders }}"
bind_zones: 
  - name: 'altea.es'
    create_reverse_zones: true
    primaries:
      - "{{ Gateway_dhcp }}"
    networks:
      - '10.1.1'
    name_servers: 
      - dnsserver.altea.es.
    hostmaster_email: admin
    hosts:
      - name: dnsserver
        ip: "{{ Gateway_dhcp }}"
      - name: cliXubuntu
        ip: "{{ IP_fija_cliente }}"
  - name: 'raul.es'
    type: secondary
    create_reverse_zones: true
    primaries:
      - "{{ GW }}"

## Para la práctica 4.4
#=======================
port: 80
server_name: webserver2
document_root: /var/www
app_root: balanceo
basic_auth: false
restr_IP: false
rev_proxy: true
balanceo: true

balanceo1: webserver1
balanceo2: webserver2